<?php
/**
 * CampaignTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CollingMedia\StackAdapt
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * StackAdapt API
 *
 * Use this API to create Native Ads and Campaigns on the StackAdapt Platform Use this API to create Native Ads and Campaigns on the StackAdapt Platform
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CollingMedia\StackAdapt;

/**
 * CampaignTest Class Doc Comment
 *
 * @category    Class */
// * @description Campaign
/**
 * @package     CollingMedia\StackAdapt
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CampaignTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "Campaign"
     */
    public function testCampaign()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "advertiser_id"
     */
    public function testPropertyAdvertiserId()
    {

    }

    /**
     * Test attribute "insertion_order_id"
     */
    public function testPropertyInsertionOrderId()
    {

    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {

    }

    /**
     * Test attribute "budget"
     */
    public function testPropertyBudget()
    {

    }

    /**
     * Test attribute "bid_type"
     */
    public function testPropertyBidType()
    {

    }

    /**
     * Test attribute "bid_amount_total"
     */
    public function testPropertyBidAmountTotal()
    {

    }

    /**
     * Test attribute "optimize_type"
     */
    public function testPropertyOptimizeType()
    {

    }

    /**
     * Test attribute "optimize_value"
     */
    public function testPropertyOptimizeValue()
    {

    }

    /**
     * Test attribute "daily_cap"
     */
    public function testPropertyDailyCap()
    {

    }

    /**
     * Test attribute "pace_evenly"
     */
    public function testPropertyPaceEvenly()
    {

    }

    /**
     * Test attribute "state"
     */
    public function testPropertyState()
    {

    }

    /**
     * Test attribute "start_date"
     */
    public function testPropertyStartDate()
    {

    }

    /**
     * Test attribute "end_date"
     */
    public function testPropertyEndDate()
    {

    }

    /**
     * Test attribute "category_options"
     */
    public function testPropertyCategoryOptions()
    {

    }

    /**
     * Test attribute "country_options"
     */
    public function testPropertyCountryOptions()
    {

    }

    /**
     * Test attribute "us_state_options"
     */
    public function testPropertyUsStateOptions()
    {

    }

    /**
     * Test attribute "canada_province_options"
     */
    public function testPropertyCanadaProvinceOptions()
    {

    }

    /**
     * Test attribute "city_options"
     */
    public function testPropertyCityOptions()
    {

    }

    /**
     * Test attribute "domain_action"
     */
    public function testPropertyDomainAction()
    {

    }

    /**
     * Test attribute "domain_options"
     */
    public function testPropertyDomainOptions()
    {

    }

    /**
     * Test attribute "device_type_options"
     */
    public function testPropertyDeviceTypeOptions()
    {

    }

    /**
     * Test attribute "supply_type_options"
     */
    public function testPropertySupplyTypeOptions()
    {

    }

    /**
     * Test attribute "supply_source_options"
     */
    public function testPropertySupplySourceOptions()
    {

    }

    /**
     * Test attribute "freq_cap_limit"
     */
    public function testPropertyFreqCapLimit()
    {

    }

    /**
     * Test attribute "freq_cap_time"
     */
    public function testPropertyFreqCapTime()
    {

    }

    /**
     * Test attribute "language_options"
     */
    public function testPropertyLanguageOptions()
    {

    }

    /**
     * Test attribute "use_dma"
     */
    public function testPropertyUseDma()
    {

    }

    /**
     * Test attribute "conversion_trackers"
     */
    public function testPropertyConversionTrackers()
    {

    }

    /**
     * Test attribute "allow_iframe_engagement"
     */
    public function testPropertyAllowIframeEngagement()
    {

    }

}
