<?php
/**
 * CampaignApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * StackAdapt API
 *
 * Use this API to create Native Ads and Campaigns on the StackAdapt Platform Use this API to create Native Ads and Campaigns on the StackAdapt Platform
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace CollingMedia\StackAdapt;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * CampaignApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CampaignApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for createCampaign
     *
     * Create new campaign.
     *
     */
    public function testCreateCampaign0()
    {

    }

    /**
     * Test case for createCampaign_0
     *
     * Create new campaign.
     *
     */
    public function testCreateCampaign0()
    {

    }

    /**
     * Test case for deleteCampaign
     *
     * Delete a campaign.
     *
     */
    public function testDeleteCampaign0()
    {

    }

    /**
     * Test case for deleteCampaign_0
     *
     * Delete a campaign.
     *
     */
    public function testDeleteCampaign0()
    {

    }

    /**
     * Test case for findCampaign
     *
     * Find campaign by id.
     *
     */
    public function testFindCampaign0()
    {

    }

    /**
     * Test case for findCampaign_0
     *
     * Find campaign by id.
     *
     */
    public function testFindCampaign0()
    {

    }

    /**
     * Test case for findCampaigns
     *
     * Return all campaigns.
     *
     */
    public function testFindCampaigns()
    {

    }

    /**
     * Test case for updateCampaign
     *
     * Update existing campaign.
     *
     */
    public function testUpdateCampaign0()
    {

    }

    /**
     * Test case for updateCampaign_0
     *
     * Update existing campaign.
     *
     */
    public function testUpdateCampaign0()
    {

    }

}
